#!/usr/bin/env bash
# This script configures Nginx to include a custom HTTP response header

# Update and install Nginx
apt-get update -y
apt-get install nginx -y

# Get the hostname of the server
404684-web-01=$(hostname)

# Configure Nginx to include the custom header
cat <<EOF > /etc/nginx/conf.d/custom_header.conf
server {
    listen 80;

    location / {
        add_header X-Served-By $HOSTNAME;
        proxy_pass http://localhost;
    }
}
EOF

# Test Nginx configuration for syntax errors
nginx -t

# Restart Nginx to apply the changes
service nginx reload
