#!/usr/bin/env bash
# Update package list and install HAProxy

sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure HAProxy
sudo chown $USER:USER /etc/haproxy/haproxy.cfg

echo "
frontend cryptotechcoder
bind *:80
mode http
default_backend app

backend app
    balance roundrobin
    server 404684-web-01 54.90.51.210:80 check
    server 404684-web-02 100.27.10.114:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
