#!/usr/bin/env bash
# Displays all active IPv4 IPs on the machine it's executed on
# Get IPv4 addresses using ifconfig and filter out loopback addresses
ifconfig | grep -oE 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1' | cut -d' ' -f2

