#!/usr/bin/env bash

# Define variables
KEY_NAME="school"
BITS=4096
PASSPHRASE="betty"

# Generate RSA key pair in OpenSSH format
ssh-keygen -t rsa -b $BITS -f $KEY_NAME -N "$PASSPHRASE" -m "PEM"

# Output success message
echo "RSA key pair generated:"
echo "Private key: $KEY_NAME"
echo "Public key: $KEY_NAME.pub"
